<?php


class model_search extends Model
{
    public function get_data(): ?array
    {
        parent::get_data(); // TODO: Change the autogenerated stub
    }

    public function get_data_filtered($name): ?array
    {
        $data = array("ingredients" => array(), "cocktails" => array());

        $dbo = new PDO('mysql:dbname=elgusto_main;host=averkin.tim',
            'test_user',
            '',
            array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8'"));

        $cocktail_array = array();
        $sth = $dbo->prepare("SELECT * FROM ingredients WHERE NAME LIKE :item");
        $sth->execute(array('item' => $name));
        while ($required_array = $sth->fetch(PDO::FETCH_ASSOC)) {
            str_replace(' ', '', $required_array['FileName']);
            array_push($cocktail_array, $required_array);
        }

        $data["ingredients"] = $cocktail_array;


        $dbo = new PDO('mysql:dbname=elgusto_main;host=averkin.tim',
            'test_user',
            '',
            array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8'"));

        $cocktail_array = array();
        $sth = $dbo->prepare("SELECT * FROM cocktails WHERE NAME LIKE :item");
        $sth->execute(array('item' => $name));
        while ($required_array = $sth->fetch(PDO::FETCH_ASSOC)) {
            $call_ingredients = $dbo->prepare("SELECT * FROM recipe WHERE cocktailID = :current");
            $call_ingredients->execute(array('current' => $required_array['ID']));

            $required_array['Recipe'] = array();
            while ($recipe_element = $call_ingredients->fetch(PDO::FETCH_ASSOC))
            {
                $call_recipe = $dbo->prepare("SELECT * FROM ingredients WHERE ID = :id");
                $call_recipe->execute(array('id' => $recipe_element['ingredientID']));
                $ingredient = array();
                $ingredient["ingredient"] = $call_recipe->fetch(PDO::FETCH_ASSOC);
                $ingredient["measure"] = $recipe_element["measure"];
                $ingredient["count"] = $recipe_element["count"];
                array_push( $required_array['Recipe'], $ingredient);
            }

            $required_array['Steps'] = explode(".", $required_array['Steps']);
            $required_array['Categories'] = array();
            array_push(
                $required_array['Categories'],
                $required_array['Strong'],
                $required_array['Taste'],
                $required_array['Base']);
            array_push($cocktail_array, $required_array);
        }

        $data["cocktails"] = $cocktail_array;

        return $data;
    }
}